automatic_submission: true
award: UM1HG009443
biosample: ENCBS759QMD
description: Illumina short-read B6/Cast F1 gastrocnemius P14 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR581NLU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB173NDS:
    read1:
    - ENCFF157MWD
    read2:
    - ENCFF703EUI
  ENCLB567RWD:
    read1:
    - ENCFF077YBZ
    read2:
    - ENCFF914CFO
  ENCLB700PHX:
    read1:
    - ENCFF239VAO
    read2:
    - ENCFF660OIT
  ENCLB865NBC:
    read1:
    - ENCFF349BPV
    read2:
    - ENCFF615AST
  ENCLB993HSH:
    read1:
    - ENCFF171HWC
    read2:
    - ENCFF021PNM
mem_mb: 65536
stranded: Forward
