automatic_submission: true
award: UM1HG009443
biosample: ENCBS164HJY
description: Illumina short-read B6/Cast F1 gastrocnemius P10 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR667UMR
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB033OJL:
    read1:
    - ENCFF283LHY
    read2:
    - ENCFF116CGV
  ENCLB349RNZ:
    read1:
    - ENCFF348MYY
    read2:
    - ENCFF718GAP
  ENCLB388PMA:
    read1:
    - ENCFF101LIQ
    read2:
    - ENCFF707XUE
  ENCLB908URC:
    read1:
    - ENCFF373JRC
    read2:
    - ENCFF443ODW
  ENCLB912FFI:
    read1:
    - ENCFF143GRU
    read2:
    - ENCFF626KKI
mem_mb: 65536
stranded: Forward
