automatic_submission: true
award: UM1HG009443
biosample: ENCBS149DQX
description: Illumina short-read B6/Cast F1 heart P25 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR764CYB
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB215MXD:
    read1:
    - ENCFF702TPY
    read2:
    - ENCFF220SCF
  ENCLB602ENZ:
    read1:
    - ENCFF135PZD
    read2:
    - ENCFF732HWS
  ENCLB759IBF:
    read1:
    - ENCFF140TQG
    read2:
    - ENCFF983EPH
  ENCLB779ZKC:
    read1:
    - ENCFF365GVP
    read2:
    - ENCFF917AZV
mem_mb: 65536
stranded: Forward
