automatic_submission: true
award: UM1HG009443
description: short-read deep Split-seq single-nucleus myotube 1,000 cell lib
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR572SMD
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library_accession: ENCLB273ZWE
mem_mb: 65536
read1:
- ENCFF371HWX
read2:
- ENCFF774YQQ
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
