automatic_submission: true
award: UM1HG009443
biosample: ENCBS880FWQ
description: Illumina short-read B6/Cast F1 gastrocnemius P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR576UHY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB369CIJ:
    read1:
    - ENCFF092FKI
    read2:
    - ENCFF399EKV
  ENCLB422BTQ:
    read1:
    - ENCFF889KQL
    read2:
    - ENCFF108CJW
  ENCLB588PHF:
    read1:
    - ENCFF364LTV
    read2:
    - ENCFF412MZL
  ENCLB774WTZ:
    read1:
    - ENCFF881ZYV
    read2:
    - ENCFF649UHO
  ENCLB878CTA:
    read1:
    - ENCFF550MFN
    read2:
    - ENCFF742AQP
mem_mb: 65536
stranded: Forward
