automatic_submission: true
award: UM1HG009443
biosample: ENCBS219MZB
description: Illumina short-read 5xFAD/Cast F1 gastrocnemius P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR571QJI
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB322BLG:
    read1:
    - ENCFF194JPV
    read2:
    - ENCFF327ICG
  ENCLB389DOH:
    read1:
    - ENCFF919XUP
    read2:
    - ENCFF664NFX
  ENCLB469JOS:
    read1:
    - ENCFF614KBW
    read2:
    - ENCFF950QFW
  ENCLB576NCQ:
    read1:
    - ENCFF795MYC
    read2:
    - ENCFF240UPN
  ENCLB698NKE:
    read1:
    - ENCFF076PZW
    read2:
    - ENCFF877WIB
  ENCLB881UEH:
    read1:
    - ENCFF884QYQ
    read2:
    - ENCFF335GVS
mem_mb: 65536
stranded: Forward
