automatic_submission: true
award: UM1HG009443
biosample: ENCBS929ZLW
description: Illumina short-read B6/Cast F1 hippocampus P25 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR399EUZ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB154YPJ:
    read1:
    - ENCFF908VJB
    read2:
    - ENCFF724JMI
  ENCLB359PID:
    read1:
    - ENCFF774WUS
    read2:
    - ENCFF660CBQ
  ENCLB369IQW:
    read1:
    - ENCFF062EEP
    read2:
    - ENCFF958ARA
  ENCLB658FCF:
    read1:
    - ENCFF592OPF
    read2:
    - ENCFF499JYX
  ENCLB792GGZ:
    read1:
    - ENCFF401YLD
    read2:
    - ENCFF653APO
mem_mb: 65536
stranded: Forward
