automatic_submission: true
award: UM1HG009443
biosample: ENCBS136GTT
description: Illumina short-read B6/Cast F1 cortex P18-20mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR308DHB
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB091RDJ:
    read1:
    - ENCFF963CMY
    read2:
    - ENCFF388HDQ
  ENCLB311BRJ:
    read1:
    - ENCFF381VPZ
    read2:
    - ENCFF519LQI
  ENCLB448HRX:
    read1:
    - ENCFF490UXH
    read2:
    - ENCFF487RPD
  ENCLB812HTK:
    read1:
    - ENCFF187WIC
    read2:
    - ENCFF470BNP
  ENCLB838SQN:
    read1:
    - ENCFF976ARZ
    read2:
    - ENCFF663XPE
  ENCLB925MFS:
    read1:
    - ENCFF259EZP
    read2:
    - ENCFF599MBG
mem_mb: 65536
stranded: Forward
