automatic_submission: true
award: UM1HG009443
biosample: ENCBS002BZK
description: Illumina short-read B6/Cast F1 gastrocnemius P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR627XNK
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB025OFW:
    read1:
    - ENCFF604JMP
    read2:
    - ENCFF365OYF
  ENCLB509TLV:
    read1:
    - ENCFF119TZS
    read2:
    - ENCFF398FJM
  ENCLB736IFQ:
    read1:
    - ENCFF369EPU
    read2:
    - ENCFF903XGU
  ENCLB884EAH:
    read1:
    - ENCFF946LWI
    read2:
    - ENCFF076VSJ
  ENCLB969DID:
    read1:
    - ENCFF147TIE
    read2:
    - ENCFF820EDL
mem_mb: 65536
stranded: Forward
