automatic_submission: true
award: UM1HG009443
description: Please note that this experiment is part of 10x multiome and has a corresponding
  scATAC experiment (ENCSR229VVY).
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR472RRP
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB578ADC
mem_mb: 65536
read1:
- ENCFF923NIZ
- ENCFF142KFD
read2:
- ENCFF866QMI
- ENCFF823GMJ
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
