automatic_submission: true
award: UM1HG009443
biosample: ENCBS039LEW
description: Illumina short-read B6/Cast F1 hippocampus P8mo female 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR819UHV
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB110RLE:
    read1:
    - ENCFF413NKU
    read2:
    - ENCFF320VTR
  ENCLB153UAN:
    read1:
    - ENCFF431EBR
    read2:
    - ENCFF626BJH
  ENCLB197PIN:
    read1:
    - ENCFF192NBX
    read2:
    - ENCFF915TBA
  ENCLB215CYF:
    read1:
    - ENCFF764FUB
    read2:
    - ENCFF828WEL
  ENCLB439PMI:
    read1:
    - ENCFF269NCW
    read2:
    - ENCFF892DGP
  ENCLB465DOJ:
    read1:
    - ENCFF604OPJ
    read2:
    - ENCFF531NKM
mem_mb: 65536
stranded: Forward
