automatic_submission: true
award: UM1HG009443
biosample: ENCBS973VUK
description: Illumina short-read B6/Cast F1 gastrocnemius P10 male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR653HPZ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB588YYL:
    read1:
    - ENCFF469XDY
    read2:
    - ENCFF317HLV
  ENCLB936ACJ:
    read1:
    - ENCFF253MYW
    read2:
    - ENCFF448CSR
mem_mb: 65536
stranded: Forward
