automatic_submission: true
award: UM1HG009443
biosample: ENCBS471TDE
description: Illumina short-read B6/Cast F1 gastrocnemius P2mo male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR150KKS
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB231VZQ:
    read1:
    - ENCFF691SFV
    read2:
    - ENCFF591UKR
  ENCLB647DIU:
    read1:
    - ENCFF165PJB
    read2:
    - ENCFF973BFU
mem_mb: 65536
stranded: Forward
