automatic_submission: true
award: UM1HG009443
biosample: ENCBS619GLX
description: Illumina short-read 5xFAD/Cast F1 hippocampus P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR581ZDJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB084YDI:
    read1:
    - ENCFF639WTV
    read2:
    - ENCFF344GQK
  ENCLB169JOS:
    read1:
    - ENCFF093NWX
    read2:
    - ENCFF020TLV
  ENCLB301TOI:
    read1:
    - ENCFF714RIB
    read2:
    - ENCFF293JNE
  ENCLB484IBF:
    read1:
    - ENCFF809MDZ
    read2:
    - ENCFF462ZXE
  ENCLB631EQI:
    read1:
    - ENCFF192GKC
    read2:
    - ENCFF903ZVW
  ENCLB763WUH:
    read1:
    - ENCFF207HUM
    read2:
    - ENCFF179CJM
mem_mb: 65536
stranded: Forward
