automatic_submission: true
award: UM1HG009443
biosample: ENCBS135NXY
description: Illumina short-read B6/Cast F1 heart P14 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR041KFB
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB552FVN:
    read1:
    - ENCFF269CHB
    read2:
    - ENCFF923IHV
  ENCLB643OAR:
    read1:
    - ENCFF559TOF
    read2:
    - ENCFF525XGE
  ENCLB758KEY:
    read1:
    - ENCFF180OVT
    read2:
    - ENCFF473UJY
  ENCLB838WQF:
    read1:
    - ENCFF281OSH
    read2:
    - ENCFF670KYF
mem_mb: 65536
stranded: Forward
