automatic_submission: true
award: UM1HG009443
biosample: ENCBS613XIS
description: Illumina short-read B6/Cast F1 cortex P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR827AOS
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB133YOM:
    read1:
    - ENCFF306GRH
    read2:
    - ENCFF626XJR
  ENCLB263JBB:
    read1:
    - ENCFF657IYQ
    read2:
    - ENCFF392HVX
  ENCLB329RCA:
    read1:
    - ENCFF344DVI
    read2:
    - ENCFF830CPY
  ENCLB593XPQ:
    read1:
    - ENCFF588RPY
    read2:
    - ENCFF790MVK
  ENCLB865RYC:
    read1:
    - ENCFF792FOC
    read2:
    - ENCFF865UFF
  ENCLB922FJL:
    read1:
    - ENCFF891HXY
    read2:
    - ENCFF505SYN
mem_mb: 65536
stranded: Forward
