automatic_submission: true
award: UM1HG009443
biosample: ENCBS317KAV
description: Illumina short-read B6/Cast F1 hippocampus P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR967YET
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB106EUK:
    read1:
    - ENCFF226VCH
    read2:
    - ENCFF573PPL
  ENCLB581NMZ:
    read1:
    - ENCFF114GMG
    read2:
    - ENCFF875HMZ
  ENCLB668NNX:
    read1:
    - ENCFF079TFD
    read2:
    - ENCFF181ZPL
  ENCLB685RWW:
    read1:
    - ENCFF636SDG
    read2:
    - ENCFF565EON
  ENCLB949MPH:
    read1:
    - ENCFF091SPJ
    read2:
    - ENCFF132DHB
mem_mb: 65536
stranded: Forward
