automatic_submission: true
award: UM1HG009443
biosample: ENCBS321JYG
description: Illumina short-read B6/Cast F1 adrenal P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR396XOO
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB063SYI:
    read1:
    - ENCFF132AQX
    read2:
    - ENCFF478YMA
  ENCLB112MKY:
    read1:
    - ENCFF484QTI
    read2:
    - ENCFF510EQL
  ENCLB296HVX:
    read1:
    - ENCFF131SSU
    read2:
    - ENCFF314YEM
  ENCLB319KVG:
    read1:
    - ENCFF581ZFZ
    read2:
    - ENCFF246MLG
  ENCLB645XEO:
    read1:
    - ENCFF721GOF
    read2:
    - ENCFF043YQN
  ENCLB795GOF:
    read1:
    - ENCFF836ILF
    read2:
    - ENCFF489HED
mem_mb: 65536
stranded: Forward
