automatic_submission: true
award: UM1HG009443
biosample: ENCBS715KFN
description: Illumina short-read B6/Cast F1 heart P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR303EIR
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB173WNR:
    read1:
    - ENCFF181NLS
    read2:
    - ENCFF251GNV
  ENCLB332AQU:
    read1:
    - ENCFF022QYA
    read2:
    - ENCFF995UWF
  ENCLB361PIC:
    read1:
    - ENCFF427AGW
    read2:
    - ENCFF011TCO
  ENCLB924BWM:
    read1:
    - ENCFF327ZKL
    read2:
    - ENCFF355GDX
mem_mb: 65536
stranded: Forward
