automatic_submission: true
award: UM1HG009443
biosample: ENCBS811EFW
description: Illumina short-read B6/Cast F1 heart P14 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR041KFB
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB017OAQ:
    read1:
    - ENCFF043XMX
    read2:
    - ENCFF012KSM
  ENCLB355JWJ:
    read1:
    - ENCFF002YAG
    read2:
    - ENCFF111MYW
  ENCLB391LRK:
    read1:
    - ENCFF033ICI
    read2:
    - ENCFF002HMC
  ENCLB618NFA:
    read1:
    - ENCFF022DCM
    read2:
    - ENCFF114OPN
mem_mb: 65536
stranded: Forward
