automatic_submission: true
award: UM1HG009443
biosample: ENCBS757FVH
description: Illumina short-read B6/Cast F1 adrenal P8mo female 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR918LWU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB154IPS:
    read1:
    - ENCFF178BMT
    read2:
    - ENCFF906WQJ
  ENCLB520UGE:
    read1:
    - ENCFF553LGA
    read2:
    - ENCFF135KLL
  ENCLB628WRQ:
    read1:
    - ENCFF758DWP
    read2:
    - ENCFF969UBT
  ENCLB645TFC:
    read1:
    - ENCFF285MRW
    read2:
    - ENCFF546COU
  ENCLB700WMZ:
    read1:
    - ENCFF107BHJ
    read2:
    - ENCFF013YOU
  ENCLB894QGL:
    read1:
    - ENCFF123YEP
    read2:
    - ENCFF550LUA
mem_mb: 65536
stranded: Forward
