automatic_submission: true
award: UM1HG009443
biosample: ENCBS837RGL
description: Illumina short-read B6/Cast F1 cortex P14 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR084RQP
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB031XDH:
    read1:
    - ENCFF448ZIK
    read2:
    - ENCFF665ZEE
  ENCLB049FGC:
    read1:
    - ENCFF211NIF
    read2:
    - ENCFF222EKD
  ENCLB862ALR:
    read1:
    - ENCFF073UIU
    read2:
    - ENCFF891BBP
  ENCLB904QGH:
    read1:
    - ENCFF291BQS
    read2:
    - ENCFF448GAA
  ENCLB952NZL:
    read1:
    - ENCFF003GKS
    read2:
    - ENCFF476KBK
  ENCLB976KVP:
    read1:
    - ENCFF253MJD
    read2:
    - ENCFF246KUR
mem_mb: 65536
stranded: Forward
