# cDNA
read1:
  - ENCFF150FBF
  - ENCFF385IAW
# barcode cell+UMI
read2:
  - ENCFF351VBS
  - ENCFF503CCI
include_intron: True
stranded: "Unstranded"
accession: "ENCLB002DZK"
umi_length: 12

#genome_dir: "~/proj/genome/GRCh38-V29-male-2.7.8a"
genome_dir: "~/proj/encode-202006-jamboree-detrout-rna-sc-pipeline/genome/GRCh38-arc2.0-2.7.8a"
#allow_list: "~/proj/illumina/cellranger-arc-2.0.0/lib/python/cellranger/barcodes/737K-arc-v1.txt.gz"
allow_list: "~/proj/encode-202006-jamboree-detrout-rna-sc-pipeline/737K-arc-v1.txt"
#star_command: "~/proj/STAR/bin/Linux_x86_64/STAR"
star_command: "~/proj/STAR/bin/Linux_x86_64_static/STAR"
outdir: "~/proj/encode-202006-jamboree-detrout-rna-sc-pipeline/adrenal/ENCSR724KET_16f_nuc/starsolo_2.7.8a_cr-compatibility/"
  
mem_mb: 131072
disk_mb: 51200
