automatic_submission: true
award: UM1HG009443
biosample: ENCBS789TOM
description: Illumina short-read B6/Cast F1 adrenal P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR111SCI
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB089NEV:
    read1:
    - ENCFF926TJC
    read2:
    - ENCFF776HYX
  ENCLB279QLV:
    read1:
    - ENCFF158IEN
    read2:
    - ENCFF421PZH
  ENCLB622VMZ:
    read1:
    - ENCFF153RLS
    read2:
    - ENCFF032SCD
  ENCLB723AAQ:
    read1:
    - ENCFF306XKZ
    read2:
    - ENCFF777LAL
  ENCLB737LHM:
    read1:
    - ENCFF753AEL
    read2:
    - ENCFF323CCW
  ENCLB984VLS:
    read1:
    - ENCFF262AAX
    read2:
    - ENCFF067NXG
mem_mb: 65536
stranded: Forward
