automatic_submission: true
award: UM1HG009443
biosample: ENCBS099STV
description: Illumina short-read B6/Cast F1 heart P14 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR938YKJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB030PDX:
    read1:
    - ENCFF035MXE
    read2:
    - ENCFF379FKG
  ENCLB243EIX:
    read1:
    - ENCFF055FKV
    read2:
    - ENCFF287SZX
  ENCLB608FDH:
    read1:
    - ENCFF042IOR
    read2:
    - ENCFF862PKA
  ENCLB673YCU:
    read1:
    - ENCFF574YHJ
    read2:
    - ENCFF406NFH
mem_mb: 65536
stranded: Forward
