automatic_submission: true
award: UM1HG009443
biosample: ENCBS837MZQ
description: Illumina short-read B6/Cast F1 gastrocnemius P2mo female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR137UJM
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB630YPY:
    read1:
    - ENCFF319TXZ
    read2:
    - ENCFF914BXM
  ENCLB718QRU:
    read1:
    - ENCFF374DQR
    read2:
    - ENCFF354QCD
mem_mb: 65536
stranded: Forward
