automatic_submission: true
award: UM1HG009443
biosample: ENCBS232ZXV
description: Illumina short-read B6/Cast F1 adrenal P8mo female 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR918LWU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB120YQW:
    read1:
    - ENCFF335ARX
    read2:
    - ENCFF223XLD
  ENCLB318SYJ:
    read1:
    - ENCFF805YRH
    read2:
    - ENCFF355TWM
  ENCLB755TMU:
    read1:
    - ENCFF781BMJ
    read2:
    - ENCFF788MVS
  ENCLB830ENZ:
    read1:
    - ENCFF256NEF
    read2:
    - ENCFF427SCN
  ENCLB873JII:
    read1:
    - ENCFF511RBR
    read2:
    - ENCFF925LKX
  ENCLB975SSO:
    read1:
    - ENCFF898FZB
    read2:
    - ENCFF740BZU
mem_mb: 65536
stranded: Forward
