automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR204RHR
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB507KDD
mem_mb: 65536
read1:
- ENCFF392ZJZ
- ENCFF295NZO
- ENCFF711AIL
- ENCFF935PUX
read2:
- ENCFF118XVV
- ENCFF822TAH
- ENCFF715WFH
- ENCFF726WIV
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
