automatic_submission: true
award: UM1HG009443
biosample: ENCBS332NCN
description: Illumina short-read B6/Cast F1 heart P18-20mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR147TEP
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB251CUK:
    read1:
    - ENCFF838FDR
    read2:
    - ENCFF145CTF
  ENCLB344JOU:
    read1:
    - ENCFF803FNC
    read2:
    - ENCFF015WCY
  ENCLB766VDZ:
    read1:
    - ENCFF139EHR
    read2:
    - ENCFF975QLU
  ENCLB850WUF:
    read1:
    - ENCFF673LVY
    read2:
    - ENCFF691ZWF
mem_mb: 65536
stranded: Forward
