automatic_submission: true
award: UM1HG009443
biosample: ENCBS600VDJ
description: Illumina short-read B6/Cast F1 hippocampus P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR079GGS
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB246BML:
    read1:
    - ENCFF982OFY
    read2:
    - ENCFF050VWY
  ENCLB408LWA:
    read1:
    - ENCFF935QZY
    read2:
    - ENCFF501SWV
  ENCLB609EYL:
    read1:
    - ENCFF917OYB
    read2:
    - ENCFF430MIV
  ENCLB662KSW:
    read1:
    - ENCFF731ARS
    read2:
    - ENCFF677WUY
  ENCLB876BRR:
    read1:
    - ENCFF813JBS
    read2:
    - ENCFF239AEB
mem_mb: 65536
stranded: Forward
