automatic_submission: true
award: UM1HG009443
description: 10X Genomics Chromium 3' single-cell RNA-Seq (v2 kit) of C57Bl6 wild-type
  15.0 day embryonic mouse proximal forelimb
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR847RRR
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: false
inclusion_accession: 737K-august-2016
lab: /labs/barbara-wold/
library_accession: ENCLB938HOJ
mem_mb: 65536
read1:
- ENCFF471WVX
read2:
- ENCFF555EDW
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 10
