automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR644VVE
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: false
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB847VJF
mem_mb: 65536
read1:
- ENCFF193GVI
- ENCFF493XYI
read2:
- ENCFF445FFL
- ENCFF602DVM
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
