automatic_submission: true
award: UM1HG009443
biosample: ENCBS709OTD
description: Illumina short-read B6/Cast F1 adrenal P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR693KAV
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB234RMO:
    read1:
    - ENCFF929MBD
    read2:
    - ENCFF909KZO
  ENCLB272YAC:
    read1:
    - ENCFF973MIQ
    read2:
    - ENCFF477MAQ
  ENCLB365EOC:
    read1:
    - ENCFF516GQF
    read2:
    - ENCFF879GNU
  ENCLB560TPK:
    read1:
    - ENCFF967VXM
    read2:
    - ENCFF948EBB
  ENCLB577ITS:
    read1:
    - ENCFF529MMA
    read2:
    - ENCFF734ZMN
  ENCLB692WDP:
    read1:
    - ENCFF369TPJ
    read2:
    - ENCFF238PWC
mem_mb: 65536
stranded: Forward
