automatic_submission: true
award: UM1HG009443
biosample: ENCBS543UZZ
description: Illumina short-read B6/Cast F1 cortex P14 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR084RQP
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB065BSJ:
    read1:
    - ENCFF167WYN
    read2:
    - ENCFF299PRL
  ENCLB281VBR:
    read1:
    - ENCFF302JAG
    read2:
    - ENCFF307PLL
  ENCLB328BQT:
    read1:
    - ENCFF543LHB
    read2:
    - ENCFF519VXA
  ENCLB399MEO:
    read1:
    - ENCFF248OTV
    read2:
    - ENCFF358MSE
  ENCLB663CRI:
    read1:
    - ENCFF089ACR
    read2:
    - ENCFF980HAW
  ENCLB998MKW:
    read1:
    - ENCFF349AEC
    read2:
    - ENCFF579EJD
mem_mb: 65536
stranded: Forward
