automatic_submission: true
award: UM1HG009443
biosample: ENCBS865MRB
description: Illumina short-read B6/Cast F1 gastrocnemius P36 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR966QJD
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB568YQY:
    read1:
    - ENCFF352JSO
    read2:
    - ENCFF706KAW
  ENCLB702IUX:
    read1:
    - ENCFF891FYK
    read2:
    - ENCFF456TPR
mem_mb: 65536
stranded: Forward
