automatic_submission: true
award: UM1HG009443
biosample: ENCBS522UXP
description: Illumina short-read B6/Cast F1 cortex P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR793HMA
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB029JFQ:
    read1:
    - ENCFF515IFN
    read2:
    - ENCFF858DNW
  ENCLB034ULA:
    read1:
    - ENCFF356LDO
    read2:
    - ENCFF044LAQ
  ENCLB142MZF:
    read1:
    - ENCFF027YJT
    read2:
    - ENCFF587GQY
  ENCLB468WUV:
    read1:
    - ENCFF094VCD
    read2:
    - ENCFF233FKX
  ENCLB616NPS:
    read1:
    - ENCFF933JFS
    read2:
    - ENCFF417FBY
  ENCLB955TVD:
    read1:
    - ENCFF599JFM
    read2:
    - ENCFF829KPY
mem_mb: 65536
stranded: Forward
