automatic_submission: true
award: UM1HG009443
biosample: ENCBS521SGC
description: Illumina short-read B6/Cast F1 gastrocnemius P4 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR627PLH
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB399PQQ:
    read1:
    - ENCFF384ONL
    read2:
    - ENCFF684CGL
  ENCLB573VOO:
    read1:
    - ENCFF875FUF
    read2:
    - ENCFF100BRE
  ENCLB602PVM:
    read1:
    - ENCFF698DKG
    read2:
    - ENCFF187YYT
  ENCLB718CLF:
    read1:
    - ENCFF407QPK
    read2:
    - ENCFF071TFF
  ENCLB913VRW:
    read1:
    - ENCFF458SKD
    read2:
    - ENCFF584ABY
mem_mb: 65536
stranded: Forward
