automatic_submission: true
award: UM1HG009443
biosample: ENCBS174PCZ
description: Illumina short-read B6/Cast F1 cortex P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR839BHY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB027FOK:
    read1:
    - ENCFF558THE
    read2:
    - ENCFF955VEI
  ENCLB121XTD:
    read1:
    - ENCFF725ITM
    read2:
    - ENCFF921GLY
  ENCLB210PTX:
    read1:
    - ENCFF472OUN
    read2:
    - ENCFF336ZWM
  ENCLB405QDU:
    read1:
    - ENCFF279VYR
    read2:
    - ENCFF814MVB
  ENCLB821ELA:
    read1:
    - ENCFF427OMC
    read2:
    - ENCFF539WSV
  ENCLB990OKU:
    read1:
    - ENCFF960WYJ
    read2:
    - ENCFF996JOI
mem_mb: 65536
stranded: Forward
