automatic_submission: true
award: UM1HG009443
biosample: ENCBS180IZM
description: Illumina short-read B6/Cast F1 gastrocnemius P10 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR253YLA
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB145UXM:
    read1:
    - ENCFF821HMJ
    read2:
    - ENCFF323TGU
  ENCLB699IMY:
    read1:
    - ENCFF868ZER
    read2:
    - ENCFF024KDD
mem_mb: 65536
stranded: Forward
