automatic_submission: true
award: UM1HG009443
biosample: ENCBS740HOX
description: Illumina short-read B6/Cast F1 heart P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR617CNE
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB106FZX:
    read1:
    - ENCFF708NGK
    read2:
    - ENCFF859KWY
  ENCLB560RHI:
    read1:
    - ENCFF644ZXI
    read2:
    - ENCFF419SXJ
  ENCLB694RNA:
    read1:
    - ENCFF963OBW
    read2:
    - ENCFF577SWF
  ENCLB759DIN:
    read1:
    - ENCFF521IAH
    read2:
    - ENCFF679SQY
mem_mb: 65536
stranded: Forward
