automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
#encode_portal_host: test.encodedcc.org
experiment_accession: ENCSR298MPV
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB814OYP
mem_mb: 65536
read1:
- ENCFF004YJN
- ENCFF187NXK
read2:
- ENCFF792KCT
- ENCFF929NWF
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
