automatic_submission: true
award: UM1HG009443
biosample: ENCBS400OJZ
description: Illumina short-read B6/Cast F1 adrenal P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR409OGG
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB016WMT:
    read1:
    - ENCFF177RQI
    read2:
    - ENCFF429XCH
  ENCLB645GDV:
    read1:
    - ENCFF731RYJ
    read2:
    - ENCFF064YMN
  ENCLB655MEY:
    read1:
    - ENCFF055NVX
    read2:
    - ENCFF538VZY
  ENCLB798XOZ:
    read1:
    - ENCFF096PVP
    read2:
    - ENCFF588JBI
  ENCLB886UOC:
    read1:
    - ENCFF162SCZ
    read2:
    - ENCFF898RJS
  ENCLB999GKK:
    read1:
    - ENCFF220USQ
    read2:
    - ENCFF009PFW
mem_mb: 65536
stranded: Forward
