automatic_submission: true
award: UM1HG009443
biosample: ENCBS554AFJ
description: Illumina short-read B6/Cast F1 hippocampus P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR203XJO
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB175XVH:
    read1:
    - ENCFF170LJT
    read2:
    - ENCFF210FWR
  ENCLB351VZT:
    read1:
    - ENCFF835FYR
    read2:
    - ENCFF912KWV
  ENCLB393NYF:
    read1:
    - ENCFF988NLW
    read2:
    - ENCFF202UUB
  ENCLB690SEK:
    read1:
    - ENCFF574DYI
    read2:
    - ENCFF860OLL
  ENCLB856XKJ:
    read1:
    - ENCFF896MVF
    read2:
    - ENCFF351AGK
mem_mb: 65536
stranded: Forward
