automatic_submission: true
award: UM1HG009443
biosample: ENCBS888VUS
description: Illumina short-read B6/Cast F1 gastrocnemius P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR488XVC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB099WXZ:
    read1:
    - ENCFF127MYM
    read2:
    - ENCFF869WVF
  ENCLB415YUB:
    read1:
    - ENCFF996OBK
    read2:
    - ENCFF121WBW
  ENCLB654UZJ:
    read1:
    - ENCFF170AIJ
    read2:
    - ENCFF432LAY
  ENCLB795XOX:
    read1:
    - ENCFF834SMS
    read2:
    - ENCFF364SNQ
  ENCLB859WWU:
    read1:
    - ENCFF701NZF
    read2:
    - ENCFF429XQM
mem_mb: 65536
stranded: Forward
