automatic_submission: true
award: UM1HG009443
biosample: ENCBS373TUO
description: Illumina short-read B6/Cast F1 gastrocnemius P4 male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR328JOY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB076UPJ:
    read1:
    - ENCFF391MOI
    read2:
    - ENCFF844MNY
  ENCLB582IOU:
    read1:
    - ENCFF015BNQ
    read2:
    - ENCFF888QZA
mem_mb: 65536
stranded: Forward
