automatic_submission: true
award: UM1HG009443
biosample: ENCBS221WCD
description: Illumina short-read B6/Cast F1 cortex P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR160VMU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB197WGP:
    read1:
    - ENCFF665DZW
    read2:
    - ENCFF396CDM
  ENCLB257CXI:
    read1:
    - ENCFF422MDB
    read2:
    - ENCFF446RTB
  ENCLB414MRM:
    read1:
    - ENCFF315XIM
    read2:
    - ENCFF986OQV
  ENCLB601FXL:
    read1:
    - ENCFF097NAX
    read2:
    - ENCFF745BWT
  ENCLB796CWD:
    read1:
    - ENCFF499CDB
    read2:
    - ENCFF602ARA
  ENCLB827DWK:
    read1:
    - ENCFF035KRP
    read2:
    - ENCFF293ZVW
mem_mb: 65536
stranded: Forward
