automatic_submission: true
award: UM1HG009443
biosample: ENCBS077XIS
description: Illumina short-read B6/Cast F1 gastrocnemius P18-20mo male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR480RWU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB516QGH:
    read1:
    - ENCFF492QAG
    read2:
    - ENCFF112HBU
  ENCLB774LQA:
    read1:
    - ENCFF858ZHH
    read2:
    - ENCFF554APM
mem_mb: 65536
stranded: Forward
