automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR788SNY
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB900EOL
mem_mb: 65536
read1:
- ENCFF242KXL
- ENCFF881WLP
- ENCFF247RQP
- ENCFF122BLU
read2:
- ENCFF335CMO
- ENCFF443MBK
- ENCFF931PKP
- ENCFF036ZHC
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
