automatic_submission: true
award: UM1HG009443
biosample: ENCBS356FYU
description: Illumina short-read B6/Cast F1 heart P4 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR266RTS
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB097ZGJ:
    read1:
    - ENCFF377LSI
    read2:
    - ENCFF624NMY
  ENCLB731YVH:
    read1:
    - ENCFF179JZA
    read2:
    - ENCFF675WAH
  ENCLB797NXF:
    read1:
    - ENCFF562NLC
    read2:
    - ENCFF507IOO
  ENCLB928QUX:
    read1:
    - ENCFF155XRO
    read2:
    - ENCFF659UYA
mem_mb: 65536
stranded: Forward
