automatic_submission: true
award: UM1HG009443
biosample: ENCBS963ZVP
description: Illumina short-read B6/Cast F1 gastrocnemius P14 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR462NDO
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB294GCN:
    read1:
    - ENCFF018QSP
    read2:
    - ENCFF012FQF
  ENCLB801VRN:
    read1:
    - ENCFF683PDX
    read2:
    - ENCFF179LQU
mem_mb: 65536
stranded: Forward
