automatic_submission: true
award: UM1HG009443
biosample: ENCBS246YKO
description: Illumina short-read B6/Cast F1 hippocampus P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR435CMT
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB268IIG:
    read1:
    - ENCFF932CLL
    read2:
    - ENCFF442HGC
  ENCLB273YCJ:
    read1:
    - ENCFF974FQI
    read2:
    - ENCFF260QMA
  ENCLB663AJA:
    read1:
    - ENCFF903MDW
    read2:
    - ENCFF489AXB
  ENCLB804SGS:
    read1:
    - ENCFF801INS
    read2:
    - ENCFF571QUU
  ENCLB868SXB:
    read1:
    - ENCFF543GWT
    read2:
    - ENCFF498OAB
mem_mb: 65536
stranded: Forward
