automatic_submission: true
award: UM1HG009443
biosample: ENCBS180IZM
description: Illumina short-read B6/Cast F1 gastrocnemius P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR554FGW
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB032AUQ:
    read1:
    - ENCFF052MAR
    read2:
    - ENCFF366BZP
  ENCLB411QYO:
    read1:
    - ENCFF881NOR
    read2:
    - ENCFF200MGF
  ENCLB721ZIN:
    read1:
    - ENCFF507LTP
    read2:
    - ENCFF603ZKM
  ENCLB931FBH:
    read1:
    - ENCFF949PIY
    read2:
    - ENCFF196CXY
  ENCLB977BKG:
    read1:
    - ENCFF851FSQ
    read2:
    - ENCFF889AML
mem_mb: 65536
stranded: Forward
