automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR835JFN
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB089YWN
mem_mb: 65536
read1:
- ENCFF922EEA
- ENCFF324YXY
read2:
- ENCFF051ZEH
- ENCFF133FIQ
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
