automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR654MFX
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB779BCG
mem_mb: 65536
read1:
- ENCFF818XLR
- ENCFF550LUQ
- ENCFF852DCT
- ENCFF454JZJ
read2:
- ENCFF161ZOQ
- ENCFF943GZD
- ENCFF648CYQ
- ENCFF769IUO
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
