automatic_submission: true
award: UM1HG009443
biosample: ENCBS434NYG
description: Illumina short-read B6/Cast F1 hippocampus P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR569LJC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB116AYK:
    read1:
    - ENCFF184YBZ
    read2:
    - ENCFF381SKL
  ENCLB256BNN:
    read1:
    - ENCFF838XNG
    read2:
    - ENCFF130BKV
  ENCLB403OAX:
    read1:
    - ENCFF824JBX
    read2:
    - ENCFF328NXK
  ENCLB893QZK:
    read1:
    - ENCFF297IIQ
    read2:
    - ENCFF220KWE
  ENCLB930FEO:
    read1:
    - ENCFF118ECF
    read2:
    - ENCFF599CJQ
mem_mb: 65536
stranded: Forward
