automatic_submission: true
award: UM1HG009443
description: snRNA on left lobe of liver. Please note that this experiment is part
  of 10x multiome and has a correspoding scATAC experiment (ENCSR139ATR).
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR369UFT
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB335ITX
mem_mb: 65536
read1:
- ENCFF579PTX
- ENCFF923ZAO
read2:
- ENCFF907MUD
- ENCFF793AYK
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
