automatic_submission: true
award: UM1HG009443
biosample: ENCBS837MZQ
description: Illumina short-read B6/Cast F1 gastrocnemius P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR576UHY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB177NKV:
    read1:
    - ENCFF287UVU
    read2:
    - ENCFF349LDP
  ENCLB225LQC:
    read1:
    - ENCFF896SUI
    read2:
    - ENCFF361HJJ
  ENCLB605JDY:
    read1:
    - ENCFF896FLD
    read2:
    - ENCFF757LVS
  ENCLB720UQD:
    read1:
    - ENCFF834HLV
    read2:
    - ENCFF069LUV
  ENCLB928GCB:
    read1:
    - ENCFF410EKH
    read2:
    - ENCFF356BCP
mem_mb: 65536
stranded: Forward
