automatic_submission: true
award: UM1HG009443
biosample: ENCBS711QUR
description: Illumina short-read B6/Cast F1 adrenal P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR396XOO
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB181AJI:
    read1:
    - ENCFF578OAR
    read2:
    - ENCFF163FFS
  ENCLB216BZE:
    read1:
    - ENCFF550LDS
    read2:
    - ENCFF654TGZ
  ENCLB319EVD:
    read1:
    - ENCFF073WEP
    read2:
    - ENCFF025SJA
  ENCLB416TFO:
    read1:
    - ENCFF087KFE
    read2:
    - ENCFF990GSD
  ENCLB738LIQ:
    read1:
    - ENCFF876VWD
    read2:
    - ENCFF549LSB
  ENCLB759DXI:
    read1:
    - ENCFF671ZVD
    read2:
    - ENCFF789KRK
mem_mb: 65536
stranded: Forward
