automatic_submission: true
award: UM1HG009443
biosample: ENCBS743KNR
description: Illumina short-read B6/Cast F1 gastrocnemius P18-20mo female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR279GBC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB583LMV:
    read1:
    - ENCFF680FLT
    read2:
    - ENCFF703JPD
  ENCLB595WEW:
    read1:
    - ENCFF188XPE
    read2:
    - ENCFF322WLX
mem_mb: 65536
stranded: Forward
