automatic_submission: true
award: UM1HG009443
biosample: ENCBS043EST
description: Illumina short-read B6/Cast F1 cortex P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR839BHY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB214RIA:
    read1:
    - ENCFF687BEN
    read2:
    - ENCFF708VWY
  ENCLB246KVH:
    read1:
    - ENCFF171XIZ
    read2:
    - ENCFF311ZRR
  ENCLB316HYI:
    read1:
    - ENCFF723VWE
    read2:
    - ENCFF470IJK
  ENCLB594NUU:
    read1:
    - ENCFF437NQE
    read2:
    - ENCFF859HTC
  ENCLB833LMV:
    read1:
    - ENCFF842GSL
    read2:
    - ENCFF355SSY
  ENCLB861LSX:
    read1:
    - ENCFF452IWW
    read2:
    - ENCFF715PUP
mem_mb: 65536
stranded: Forward
