automatic_submission: true
award: UM1HG009443
biosample: ENCBS888VUS
description: Illumina short-read B6/Cast F1 gastrocnemius P36 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR966QJD
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB007ICU:
    read1:
    - ENCFF932OPQ
    read2:
    - ENCFF619VYZ
  ENCLB103KCU:
    read1:
    - ENCFF443WMO
    read2:
    - ENCFF725NDK
mem_mb: 65536
stranded: Forward
