automatic_submission: true
award: UM1HG009443
biosample: ENCBS819SOQ
description: Illumina short-read B6/Cast F1 cortex P14 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR118FCJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB096OHB:
    read1:
    - ENCFF445GUI
    read2:
    - ENCFF867ZCO
  ENCLB141HOZ:
    read1:
    - ENCFF839QNN
    read2:
    - ENCFF803BFL
  ENCLB290SWQ:
    read1:
    - ENCFF234TNA
    read2:
    - ENCFF866RVD
  ENCLB321GSN:
    read1:
    - ENCFF072GND
    read2:
    - ENCFF532EXO
  ENCLB455PAL:
    read1:
    - ENCFF039QLS
    read2:
    - ENCFF135YLG
  ENCLB892PQW:
    read1:
    - ENCFF675GRZ
    read2:
    - ENCFF004OLK
mem_mb: 65536
stranded: Forward
