automatic_submission: true
award: UM1HG009443
biosample: ENCBS196YFO
description: Illumina short-read B6/Cast F1 cortex P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR450IJU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB058JIG:
    read1:
    - ENCFF878HQK
    read2:
    - ENCFF766QYV
  ENCLB270PXC:
    read1:
    - ENCFF700AVW
    read2:
    - ENCFF487SYQ
  ENCLB458AZE:
    read1:
    - ENCFF286QLU
    read2:
    - ENCFF431RPZ
  ENCLB504CPJ:
    read1:
    - ENCFF818QVT
    read2:
    - ENCFF363UKB
  ENCLB518DXN:
    read1:
    - ENCFF326IRO
    read2:
    - ENCFF220TFC
  ENCLB784UHT:
    read1:
    - ENCFF819EMA
    read2:
    - ENCFF685HHP
mem_mb: 65536
stranded: Forward
