automatic_submission: true
award: UM1HG009443
biosample: ENCBS510JLV
description: Illumina short-read B6/Cast F1 cortex P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR793HMA
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB199EXA:
    read1:
    - ENCFF665DSQ
    read2:
    - ENCFF267NKQ
  ENCLB241TJF:
    read1:
    - ENCFF254BVT
    read2:
    - ENCFF149IET
  ENCLB285ZLV:
    read1:
    - ENCFF242ULS
    read2:
    - ENCFF095OES
  ENCLB553KES:
    read1:
    - ENCFF571VQC
    read2:
    - ENCFF977NNG
  ENCLB963XAH:
    read1:
    - ENCFF853RME
    read2:
    - ENCFF652ASW
  ENCLB970OBM:
    read1:
    - ENCFF303VYQ
    read2:
    - ENCFF944ZIB
mem_mb: 65536
stranded: Forward
