automatic_submission: true
award: UM1HG009443
biosample: ENCBS683KKF
description: Illumina short-read B6/Cast F1 adrenal P25 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR711LRI
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB197VCG:
    read1:
    - ENCFF278RMI
    read2:
    - ENCFF433MGD
  ENCLB218CQN:
    read1:
    - ENCFF250CQO
    read2:
    - ENCFF474KDT
  ENCLB299GCX:
    read1:
    - ENCFF715EHL
    read2:
    - ENCFF474VDH
  ENCLB410WLA:
    read1:
    - ENCFF629QRX
    read2:
    - ENCFF008ZCQ
  ENCLB797FSY:
    read1:
    - ENCFF284TZC
    read2:
    - ENCFF670AVT
  ENCLB881GWL:
    read1:
    - ENCFF381LIK
    read2:
    - ENCFF787LSZ
mem_mb: 65536
stranded: Forward
