automatic_submission: true
award: UM1HG009443
biosample: ENCBS884VMI
description: Illumina short-read B6/Cast F1 gastrocnemius P2mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR047KXM
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB030GSV:
    read1:
    - ENCFF212QMY
    read2:
    - ENCFF220SDA
  ENCLB086CAA:
    read1:
    - ENCFF660IXG
    read2:
    - ENCFF037LIU
  ENCLB132IFV:
    read1:
    - ENCFF498PUG
    read2:
    - ENCFF730SGL
  ENCLB377YWJ:
    read1:
    - ENCFF840VOT
    read2:
    - ENCFF469AQN
  ENCLB708SED:
    read1:
    - ENCFF283KQS
    read2:
    - ENCFF507FPM
mem_mb: 65536
stranded: Forward
