automatic_submission: true
award: UM1HG009443
description: snRNA on human right ventricle myocardium superior. Please note that
  this experiment is part of 10x multiome and has a corresponding scATAC experiment
  (ENCSR548IRG)
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR813PWQ
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB342YHF
mem_mb: 65536
read1:
- ENCFF058QOU
- ENCFF136KEN
read2:
- ENCFF998QAH
- ENCFF963CAK
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
