automatic_submission: true
award: UM1HG009443
biosample: ENCBS955GMS
description: Illumina short-read B6/Cast F1 cortex P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR827AOS
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB154DTV:
    read1:
    - ENCFF899JIM
    read2:
    - ENCFF089WDR
  ENCLB171AWX:
    read1:
    - ENCFF886EXK
    read2:
    - ENCFF374DBL
  ENCLB177IBU:
    read1:
    - ENCFF293RQZ
    read2:
    - ENCFF508WPA
  ENCLB467TYR:
    read1:
    - ENCFF179NRD
    read2:
    - ENCFF543LQF
  ENCLB761CEJ:
    read1:
    - ENCFF622YVI
    read2:
    - ENCFF609GCP
  ENCLB841NAH:
    read1:
    - ENCFF505YSL
    read2:
    - ENCFF287KWR
mem_mb: 65536
stranded: Forward
