automatic_submission: true
award: UM1HG009443
biosample: ENCBS865NYD
description: Illumina short-read B6/Cast F1 adrenal P4 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR165FLF
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB016URT:
    read1:
    - ENCFF129YKX
    read2:
    - ENCFF174LJW
  ENCLB221HSZ:
    read1:
    - ENCFF926CCS
    read2:
    - ENCFF747SBR
  ENCLB327FIL:
    read1:
    - ENCFF799RKC
    read2:
    - ENCFF957LMZ
  ENCLB647HGC:
    read1:
    - ENCFF430BWA
    read2:
    - ENCFF658RQK
  ENCLB816NAV:
    read1:
    - ENCFF890CRT
    read2:
    - ENCFF177ABT
  ENCLB960GYI:
    read1:
    - ENCFF312HKX
    read2:
    - ENCFF227JZC
mem_mb: 65536
stranded: Forward
