automatic_submission: true
award: UM1HG009443
biosample: ENCBS825VRD
description: Illumina short-read B6/Cast F1 heart P18-20mo male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR147TEP
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB073QRO:
    read1:
    - ENCFF106WBT
    read2:
    - ENCFF911YNB
  ENCLB241AKT:
    read1:
    - ENCFF636GOE
    read2:
    - ENCFF040QPM
  ENCLB385MCZ:
    read1:
    - ENCFF320ACA
    read2:
    - ENCFF146YLG
  ENCLB750PAB:
    read1:
    - ENCFF064ZSO
    read2:
    - ENCFF721SGN
mem_mb: 65536
stranded: Forward
