automatic_submission: true
award: UM1HG009443
biosample: ENCBS231UDN
description: Illumina short-read B6/Cast F1 adrenal P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR826EHD
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB116VXR:
    read1:
    - ENCFF042CXS
    read2:
    - ENCFF286FMU
  ENCLB265BSE:
    read1:
    - ENCFF970WXK
    read2:
    - ENCFF359LDF
  ENCLB303OOK:
    read1:
    - ENCFF830HRX
    read2:
    - ENCFF196GHN
  ENCLB769QHP:
    read1:
    - ENCFF501SUK
    read2:
    - ENCFF587CSY
  ENCLB812KFX:
    read1:
    - ENCFF066VGW
    read2:
    - ENCFF809GGB
  ENCLB924BDS:
    read1:
    - ENCFF973BBW
    read2:
    - ENCFF785VXJ
mem_mb: 65536
stranded: Forward
