automatic_submission: true
award: UM1HG009443
biosample: ENCBS884WOI
description: Illumina short-read B6/Cast F1 gastrocnemius P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR627XNK
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB421TAL:
    read1:
    - ENCFF749XGR
    read2:
    - ENCFF357CZX
  ENCLB538FWY:
    read1:
    - ENCFF415GXI
    read2:
    - ENCFF128ZXV
  ENCLB860UJZ:
    read1:
    - ENCFF769RNO
    read2:
    - ENCFF016QJB
  ENCLB880UCX:
    read1:
    - ENCFF358JHD
    read2:
    - ENCFF666VVB
  ENCLB946GQA:
    read1:
    - ENCFF161RQT
    read2:
    - ENCFF442YFB
mem_mb: 65536
stranded: Forward
