automatic_submission: true
award: UM1HG009443
biosample: ENCBS236AOI
description: Illumina short-read B6/Cast F1 cortex P10 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR527LIA
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB053FYQ:
    read1:
    - ENCFF451XFH
    read2:
    - ENCFF712BVH
  ENCLB116ELG:
    read1:
    - ENCFF742CVB
    read2:
    - ENCFF314XBH
  ENCLB141HAL:
    read1:
    - ENCFF110UME
    read2:
    - ENCFF515CGL
  ENCLB643OTO:
    read1:
    - ENCFF762BCK
    read2:
    - ENCFF862LUR
  ENCLB770RDO:
    read1:
    - ENCFF293JOK
    read2:
    - ENCFF188ETK
  ENCLB838GNC:
    read1:
    - ENCFF278SFG
    read2:
    - ENCFF357UQU
mem_mb: 65536
stranded: Forward
