automatic_submission: true
award: UM1HG009443
biosample: ENCBS002BZK
description: Illumina short-read B6/Cast F1 gastrocnemius P25 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR399TQO
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB584FJZ:
    read1:
    - ENCFF974OWR
    read2:
    - ENCFF799KOO
  ENCLB746YOD:
    read1:
    - ENCFF263PNL
    read2:
    - ENCFF002PJY
mem_mb: 65536
stranded: Forward
