automatic_submission: true
award: UM1HG009443
biosample: ENCBS865MRB
description: Illumina short-read B6/Cast F1 gastrocnemius P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR488XVC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB040GWA:
    read1:
    - ENCFF121NNF
    read2:
    - ENCFF587GIP
  ENCLB285CQA:
    read1:
    - ENCFF606WLU
    read2:
    - ENCFF886QQL
  ENCLB585XVX:
    read1:
    - ENCFF721ONK
    read2:
    - ENCFF766DCL
  ENCLB826SJS:
    read1:
    - ENCFF317TPD
    read2:
    - ENCFF491GJB
  ENCLB888AUS:
    read1:
    - ENCFF192JKK
    read2:
    - ENCFF615AAZ
mem_mb: 65536
stranded: Forward
