automatic_submission: true
award: UM1HG009443
biosample: ENCBS337YRQ
description: Illumina short-read B6/Cast F1 heart P8mo female 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR145HUM
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB002OSB:
    read1:
    - ENCFF455JHY
    read2:
    - ENCFF514AMZ
  ENCLB004DVE:
    read1:
    - ENCFF151KJD
    read2:
    - ENCFF096VGK
  ENCLB035AKU:
    read1:
    - ENCFF472CUO
    read2:
    - ENCFF194WNI
  ENCLB355VJT:
    read1:
    - ENCFF322PHI
    read2:
    - ENCFF769BYS
  ENCLB625JQR:
    read1:
    - ENCFF043XXG
    read2:
    - ENCFF967FUC
  ENCLB939RMD:
    read1:
    - ENCFF859BXL
    read2:
    - ENCFF952BUA
mem_mb: 65536
stranded: Forward
