automatic_submission: true
award: UM1HG009443
biosample: ENCBS965EFJ
description: Illumina short-read B6/Cast F1 gastrocnemius P4 male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR328JOY
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB692SJM:
    read1:
    - ENCFF036YPJ
    read2:
    - ENCFF035GQL
  ENCLB712VBQ:
    read1:
    - ENCFF237PCR
    read2:
    - ENCFF764LJP
mem_mb: 65536
stranded: Forward
