automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR328GTN
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB461YMD
mem_mb: 65536
read1:
- ENCFF537MSL
- ENCFF522LOS
- ENCFF190CGR
- ENCFF200FJQ
read2:
- ENCFF174NFE
- ENCFF837QEG
- ENCFF971RNY
- ENCFF690CGM
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
