automatic_submission: true
award: UM1HG009443
description: short-read shallow Split-seq single-nucleus myotube 9,000 cell libs
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR109DAN
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library_accession: ENCLB527JDU
mem_mb: 65536
read1:
- ENCFF288PHA
read2:
- ENCFF093WFS
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
