automatic_submission: true
award: UM1HG009443
biosample: ENCBS326PIL
description: Illumina short-read B6/Cast F1 adrenal P4 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR312AOC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB262MKL:
    read1:
    - ENCFF834BQR
    read2:
    - ENCFF825WNY
  ENCLB351GFD:
    read1:
    - ENCFF253KAS
    read2:
    - ENCFF117BBP
  ENCLB534BWW:
    read1:
    - ENCFF110BFQ
    read2:
    - ENCFF198NYG
  ENCLB692UOX:
    read1:
    - ENCFF480GYA
    read2:
    - ENCFF524EYQ
  ENCLB839JPO:
    read1:
    - ENCFF818GGY
    read2:
    - ENCFF338JRY
  ENCLB898CVN:
    read1:
    - ENCFF886CXO
    read2:
    - ENCFF168OGO
mem_mb: 65536
stranded: Forward
