automatic_submission: true
award: UM1HG009443
biosample: ENCBS229UTD
description: Illumina short-read B6/Cast F1 heart P4 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR729BRE
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB153KBN:
    read1:
    - ENCFF031YZZ
    read2:
    - ENCFF094IBB
  ENCLB271MZF:
    read1:
    - ENCFF983RNL
    read2:
    - ENCFF559TWI
  ENCLB783LCA:
    read1:
    - ENCFF188DNQ
    read2:
    - ENCFF420GWA
  ENCLB905JXV:
    read1:
    - ENCFF492IZO
    read2:
    - ENCFF466YVI
mem_mb: 65536
stranded: Forward
