automatic_submission: true
award: UM1HG009443
biosample: ENCBS743KNR
description: Illumina short-read B6/Cast F1 gastrocnemius P18-20mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR927BSJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB155AFY:
    read1:
    - ENCFF291HQX
    read2:
    - ENCFF487SQH
  ENCLB271PNW:
    read1:
    - ENCFF193AST
    read2:
    - ENCFF444QQF
  ENCLB325KUC:
    read1:
    - ENCFF862VHY
    read2:
    - ENCFF198VNB
  ENCLB740EBL:
    read1:
    - ENCFF814TBK
    read2:
    - ENCFF659ATX
  ENCLB809GJH:
    read1:
    - ENCFF523SAM
    read2:
    - ENCFF352HFL
mem_mb: 65536
stranded: Forward
