# I think I'm going to try using yaml
# because in-file comments are awesome.
config_version: 1
output_dir: "~/proj/encode-202006-jamboree-detrout-rna-sc-pipeline/genome/GRCh38-arc2.0-2.7.8a"
star_dir: "~/proj/STAR/bin/Linux_x86_64_static/"
rsem_dir: "~/proj/RSEM"
refid: "GRCh38_no_alt_analysis_set_GCA_000001405.15"
annid: "cellranger-arc2.0"
spikeid: ""
fasta: "GRCh38-arc2.0-2.7.8a.fa"
gtf: "GRCh38-arc2.0-2.7.8a.gff"
name: "GRCh38-arc2.0-2.7.8a"
