automatic_submission: true
award: UM1HG009443
biosample: ENCBS052PTJ
description: Illumina short-read B6/Cast F1 heart P10 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR440PMT
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB055MKE:
    read1:
    - ENCFF365NIT
    read2:
    - ENCFF670DOU
  ENCLB107AWY:
    read1:
    - ENCFF198WBJ
    read2:
    - ENCFF713NVJ
  ENCLB773OGU:
    read1:
    - ENCFF946KLZ
    read2:
    - ENCFF025HCI
  ENCLB774KJJ:
    read1:
    - ENCFF407TNO
    read2:
    - ENCFF289MPQ
mem_mb: 65536
stranded: Forward
