automatic_submission: true
award: UM1HG009443
biosample: ENCBS266BTE
description: Illumina short-read B6/Cast F1 adrenal P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR097PDV
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB438YGP:
    read1:
    - ENCFF847PUP
    read2:
    - ENCFF028VYQ
  ENCLB587BSM:
    read1:
    - ENCFF439ILA
    read2:
    - ENCFF050ZTG
  ENCLB602PKF:
    read1:
    - ENCFF293DQK
    read2:
    - ENCFF684ZVW
  ENCLB708WAM:
    read1:
    - ENCFF618SHA
    read2:
    - ENCFF032ZAF
  ENCLB764MSD:
    read1:
    - ENCFF596QUV
    read2:
    - ENCFF154GER
  ENCLB906FKB:
    read1:
    - ENCFF803MHJ
    read2:
    - ENCFF770IHV
mem_mb: 65536
stranded: Forward
