automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR962JKS
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB845QWH
mem_mb: 65536
read1:
- ENCFF904SMD
- ENCFF516WHK
- ENCFF889YBG
- ENCFF533CRR
read2:
- ENCFF441FKY
- ENCFF309ZVS
- ENCFF242NWR
- ENCFF094RSY
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
