automatic_submission: true
award: UM1HG009443
biosample: ENCBS998IGC
description: Illumina short-read B6/Cast F1 hippocampus P25 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR569LJC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB019LZV:
    read1:
    - ENCFF849AOX
    read2:
    - ENCFF702ZMC
  ENCLB374ZKV:
    read1:
    - ENCFF849OFA
    read2:
    - ENCFF314VBF
  ENCLB494AYE:
    read1:
    - ENCFF021LHT
    read2:
    - ENCFF696UCU
  ENCLB838TLT:
    read1:
    - ENCFF419XDD
    read2:
    - ENCFF733XZH
  ENCLB962SRE:
    read1:
    - ENCFF730QVB
    read2:
    - ENCFF367FTD
mem_mb: 65536
stranded: Forward
