automatic_submission: true
award: UM1HG009443
biosample: ENCBS007OHI
description: Illumina short-read B6/Cast F1 adrenal P10 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR662TPD
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB163YGU:
    read1:
    - ENCFF964RDV
    read2:
    - ENCFF868NDC
  ENCLB280PFQ:
    read1:
    - ENCFF026UEK
    read2:
    - ENCFF127HHS
  ENCLB770UMN:
    read1:
    - ENCFF937ULR
    read2:
    - ENCFF169EPU
  ENCLB786AIU:
    read1:
    - ENCFF252OME
    read2:
    - ENCFF031TGZ
  ENCLB798EER:
    read1:
    - ENCFF203RCC
    read2:
    - ENCFF329HZZ
  ENCLB813VWF:
    read1:
    - ENCFF678FOR
    read2:
    - ENCFF217LYB
mem_mb: 65536
stranded: Forward
