automatic_submission: true
award: UM1HG009443
biosample: ENCBS521SGC
description: Illumina short-read B6/Cast F1 gastrocnemius P4 female normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR696NAL
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB477DWP:
    read1:
    - ENCFF206RDO
    read2:
    - ENCFF542RDW
  ENCLB822CYM:
    read1:
    - ENCFF370GWX
    read2:
    - ENCFF100RUU
mem_mb: 65536
stranded: Forward
