automatic_submission: true
award: UM1HG009443
biosample: ENCBS194GJK
description: Illumina short-read B6/Cast F1 adrenal P2mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR097PDV
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB031LFV:
    read1:
    - ENCFF882ZSY
    read2:
    - ENCFF624HWL
  ENCLB104HYR:
    read1:
    - ENCFF570AWT
    read2:
    - ENCFF190MAT
  ENCLB163FPQ:
    read1:
    - ENCFF775VUH
    read2:
    - ENCFF272JOK
  ENCLB651SCV:
    read1:
    - ENCFF835PVQ
    read2:
    - ENCFF613SKJ
  ENCLB713WSU:
    read1:
    - ENCFF251JQN
    read2:
    - ENCFF839HAY
  ENCLB869KHJ:
    read1:
    - ENCFF636FGD
    read2:
    - ENCFF080GCS
mem_mb: 65536
stranded: Forward
