automatic_submission: true
award: UM1HG009443
description: ''
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR749GDE
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB442AMV
mem_mb: 65536
read1:
- ENCFF959YIP
- ENCFF414TDY
read2:
- ENCFF483QXZ
- ENCFF851BFO
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
