automatic_submission: true
award: UM1HG009443
biosample: ENCBS613QQM
description: Illumina short-read B6/Cast F1 gastrocnemius P18-20mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR927BSJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB114FSY:
    read1:
    - ENCFF169NMS
    read2:
    - ENCFF143DCW
  ENCLB341KIR:
    read1:
    - ENCFF310HHQ
    read2:
    - ENCFF966IDR
  ENCLB419GUG:
    read1:
    - ENCFF016QWJ
    read2:
    - ENCFF562ZFZ
  ENCLB795NWB:
    read1:
    - ENCFF115KQD
    read2:
    - ENCFF672UWS
  ENCLB874IMM:
    read1:
    - ENCFF218GTV
    read2:
    - ENCFF473URH
mem_mb: 65536
stranded: Forward
