automatic_submission: true
award: UM1HG009443
biosample: ENCBS578PCE
description: Illumina short-read B6/Cast F1 hippocampus P10 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR846QIZ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB002WZT:
    read1:
    - ENCFF816WDR
    read2:
    - ENCFF543PDE
  ENCLB157LSK:
    read1:
    - ENCFF120HMC
    read2:
    - ENCFF353IXI
  ENCLB462RMD:
    read1:
    - ENCFF265MPE
    read2:
    - ENCFF486ZQY
  ENCLB725NDG:
    read1:
    - ENCFF245BUT
    read2:
    - ENCFF694MTN
  ENCLB875AFL:
    read1:
    - ENCFF831FRR
    read2:
    - ENCFF546INH
mem_mb: 65536
stranded: Forward
