automatic_submission: true
award: UM1HG009443
biosample: ENCBS331TRK
description: Illumina short-read B6/Cast F1 gastrocnemius P18-20mo male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR480RWU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB380IFB:
    read1:
    - ENCFF217RYD
    read2:
    - ENCFF994EBV
  ENCLB924ZIJ:
    read1:
    - ENCFF574YER
    read2:
    - ENCFF753SXM
mem_mb: 65536
stranded: Forward
