automatic_submission: true
award: UM1HG009443
biosample: ENCBS358CLR
description: Illumina short-read B6/Cast F1 heart P10 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR442NQZ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB008ELR:
    read1:
    - ENCFF385VZD
    read2:
    - ENCFF333ZLS
  ENCLB339NFS:
    read1:
    - ENCFF486BLH
    read2:
    - ENCFF441EJB
  ENCLB694VAA:
    read1:
    - ENCFF887GWT
    read2:
    - ENCFF716WFR
  ENCLB966BHG:
    read1:
    - ENCFF900GMM
    read2:
    - ENCFF310TPL
mem_mb: 65536
stranded: Forward
