automatic_submission: true
award: UM1HG009443
biosample: ENCBS399GAV
description: Illumina short-read B6/Cast F1 heart P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR594LDC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB070ZKE:
    read1:
    - ENCFF229UDA
    read2:
    - ENCFF582KXK
  ENCLB314DKP:
    read1:
    - ENCFF504VFQ
    read2:
    - ENCFF749YMS
  ENCLB497RWO:
    read1:
    - ENCFF678XCO
    read2:
    - ENCFF578CBU
  ENCLB736HVQ:
    read1:
    - ENCFF829JUJ
    read2:
    - ENCFF042WMC
mem_mb: 65536
stranded: Forward
