automatic_submission: true
award: UM1HG009443
biosample: ENCBS279BGJ
description: Illumina short-read B6/Cast F1 heart P18-20mo female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR305SPL
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB296EQF:
    read1:
    - ENCFF867KZU
    read2:
    - ENCFF735NVU
  ENCLB537OKW:
    read1:
    - ENCFF844AHR
    read2:
    - ENCFF920UED
  ENCLB749WGO:
    read1:
    - ENCFF439GJP
    read2:
    - ENCFF640CHP
  ENCLB757RSY:
    read1:
    - ENCFF470QTL
    read2:
    - ENCFF726LLY
mem_mb: 65536
stranded: Forward
