automatic_submission: true
award: UM1HG009443
description: Please note that this experiment is part of 10x multiome and has a corresponding
  scATAC experiment (ENCSR690KGJ).
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR642GFM
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 737K-arc-v1(GEX)
lab: /labs/barbara-wold/
library_accession: ENCLB986LXE
mem_mb: 65536
read1:
- ENCFF996EAO
- ENCFF262ZBZ
read2:
- ENCFF039KCP
- ENCFF943ZQR
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
