automatic_submission: true
award: UM1HG009443
biosample: ENCBS373BVD
description: Illumina short-read B6/Cast F1 hippocampus P36 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR940VCU
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB055PXE:
    read1:
    - ENCFF616JFD
    read2:
    - ENCFF436MFY
  ENCLB139TJO:
    read1:
    - ENCFF164EED
    read2:
    - ENCFF516YJJ
  ENCLB141FJQ:
    read1:
    - ENCFF849GEY
    read2:
    - ENCFF096XEX
  ENCLB438CYW:
    read1:
    - ENCFF261NEE
    read2:
    - ENCFF032TSC
  ENCLB572DYH:
    read1:
    - ENCFF382VSK
    read2:
    - ENCFF535AQN
mem_mb: 65536
stranded: Forward
