automatic_submission: true
award: UM1HG009443
description: snRNA on human right lobe of liver
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR602SGU
genome_accession: encode:starsolo-GRCh38-V29-male-index
include_intron: true
inclusion_accession: 3M-february-2018
lab: /labs/barbara-wold/
library_accession: ENCLB396URL
mem_mb: 65536
read1:
- ENCFF474XWT
- ENCFF475AKY
read2:
- ENCFF575ZNZ
- ENCFF421HXO
star_container: https://woldlab.caltech.edu/~diane/containers/star-bash-2.7.10a.sif
stranded: Forward
umi_length: 12
