automatic_submission: true
award: UM1HG009443
biosample: ENCBS713XTP
description: Illumina short-read B6/Cast F1 heart P36 female normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR594LDC
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB099NCH:
    read1:
    - ENCFF626MBJ
    read2:
    - ENCFF505ZPL
  ENCLB183WWB:
    read1:
    - ENCFF350OYO
    read2:
    - ENCFF963JST
  ENCLB791UYS:
    read1:
    - ENCFF526VRG
    read2:
    - ENCFF232KXQ
  ENCLB959LCD:
    read1:
    - ENCFF946YBH
    read2:
    - ENCFF099ZSV
mem_mb: 65536
stranded: Forward
