automatic_submission: true
award: UM1HG009443
biosample: ENCBS624IZL
description: Illumina short-read B6/Cast F1 gastrocnemius P25 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR823CLM
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB154NEL:
    read1:
    - ENCFF655OKV
    read2:
    - ENCFF305PKM
  ENCLB459PAM:
    read1:
    - ENCFF526QSZ
    read2:
    - ENCFF023WJO
  ENCLB560PJG:
    read1:
    - ENCFF916WOQ
    read2:
    - ENCFF657VLG
  ENCLB610DKC:
    read1:
    - ENCFF901MZO
    read2:
    - ENCFF278FGH
  ENCLB841NQC:
    read1:
    - ENCFF925QNS
    read2:
    - ENCFF935JVE
mem_mb: 65536
stranded: Forward
