automatic_submission: true
award: UM1HG009443
biosample: ENCBS545BQV
description: Illumina short-read B6/Cast F1 heart P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR174ZVM
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB163TZE:
    read1:
    - ENCFF204MPA
    read2:
    - ENCFF219UFI
  ENCLB229NTE:
    read1:
    - ENCFF332GVU
    read2:
    - ENCFF178NKJ
  ENCLB435OZT:
    read1:
    - ENCFF011SIS
    read2:
    - ENCFF821TNV
  ENCLB541XRJ:
    read1:
    - ENCFF976VKM
    read2:
    - ENCFF117KYY
  ENCLB687YTT:
    read1:
    - ENCFF130BNW
    read2:
    - ENCFF731BKC
  ENCLB749UBX:
    read1:
    - ENCFF542YHG
    read2:
    - ENCFF720UPT
mem_mb: 65536
stranded: Forward
