automatic_submission: true
award: UM1HG009443
biosample: ENCBS624IZL
description: Illumina short-read B6/Cast F1 gastrocnemius P25 male normal 15k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR577OFZ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB270BOP:
    read1:
    - ENCFF807BHU
    read2:
    - ENCFF007FTY
  ENCLB569AOI:
    read1:
    - ENCFF375WOY
    read2:
    - ENCFF419BUV
mem_mb: 65536
stranded: Forward
