automatic_submission: true
award: UM1HG009443
biosample: ENCBS091LPB
description: Illumina short-read B6/Cast F1 cortex P4 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR037LFG
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB448UAZ:
    read1:
    - ENCFF369XOZ
    read2:
    - ENCFF700LCL
  ENCLB517ZQZ:
    read1:
    - ENCFF549MKE
    read2:
    - ENCFF807FHX
  ENCLB557ZUK:
    read1:
    - ENCFF650FSL
    read2:
    - ENCFF334GSG
  ENCLB793OAJ:
    read1:
    - ENCFF888BBS
    read2:
    - ENCFF817WAD
  ENCLB863MDS:
    read1:
    - ENCFF363WJQ
    read2:
    - ENCFF656IJR
  ENCLB987ZVH:
    read1:
    - ENCFF059LKD
    read2:
    - ENCFF306SCB
mem_mb: 65536
stranded: Forward
