automatic_submission: true
award: UM1HG009443
biosample: ENCBS368BFZ
description: Illumina short-read B6/Cast F1 cortex P14 male normal 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR118FCJ
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB258CYJ:
    read1:
    - ENCFF879QWF
    read2:
    - ENCFF056AUY
  ENCLB291TDM:
    read1:
    - ENCFF461MVO
    read2:
    - ENCFF388RLP
  ENCLB365ZLN:
    read1:
    - ENCFF850GXX
    read2:
    - ENCFF335QCD
  ENCLB570DFI:
    read1:
    - ENCFF705XMU
    read2:
    - ENCFF151DWE
  ENCLB755ROJ:
    read1:
    - ENCFF460OTC
    read2:
    - ENCFF497BQX
  ENCLB834MCB:
    read1:
    - ENCFF006IKN
    read2:
    - ENCFF537LYB
mem_mb: 65536
stranded: Forward
