automatic_submission: true
award: UM1HG009443
biosample: ENCBS739CMN
description: Illumina short-read 5xFAD/Cast F1 heart P8mo male 8mo 12k
disk_mb: 51200
encode_portal_host: www.encodeproject.org
experiment_accession: ENCSR646KEB
genome_accession: encode:starsolo-mm10-M21-male-index
include_intron: true
inclusion_accession: encode:parse-biosciences-v1
inclusion_list_url: https://woldlab.caltech.edu/~diane/genome/parse-splitseq-v1.tar.gz
lab: /labs/barbara-wold/
library:
  ENCLB388DWZ:
    read1:
    - ENCFF183WNQ
    read2:
    - ENCFF405LHF
  ENCLB579RJZ:
    read1:
    - ENCFF043LLF
    read2:
    - ENCFF220QWC
  ENCLB873TYB:
    read1:
    - ENCFF231ZBX
    read2:
    - ENCFF007MVX
  ENCLB913QZK:
    read1:
    - ENCFF417TDB
    read2:
    - ENCFF811AUS
  ENCLB948ENL:
    read1:
    - ENCFF639TYG
    read2:
    - ENCFF667LQG
  ENCLB969AEL:
    read1:
    - ENCFF982GWK
    read2:
    - ENCFF656IAQ
mem_mb: 65536
stranded: Forward
